// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallTool(arg1, arg2) {
  return window['go']['main']['App']['CallTool'](arg1, arg2);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ConfigExists() {
  return window['go']['main']['App']['ConfigExists']();
}

export function ConnectSSE(arg1) {
  return window['go']['main']['App']['ConnectSSE'](arg1);
}

export function ConnectStdio(arg1) {
  return window['go']['main']['App']['ConnectStdio'](arg1);
}

export function ConnectStreamable(arg1) {
  return window['go']['main']['App']['ConnectStreamable'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetPrompt(arg1, arg2) {
  return window['go']['main']['App']['GetPrompt'](arg1, arg2);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListPrompts() {
  return window['go']['main']['App']['ListPrompts']();
}

export function ListResourceTemplates() {
  return window['go']['main']['App']['ListResourceTemplates']();
}

export function ListResources() {
  return window['go']['main']['App']['ListResources']();
}

export function ListTools() {
  return window['go']['main']['App']['ListTools']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function ReadResource(arg1) {
  return window['go']['main']['App']['ReadResource'](arg1);
}

export function SavePresets(arg1) {
  return window['go']['main']['App']['SavePresets'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}
