// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mcp} from '../models';
import {config} from '../models';

export function CallTool(arg1:string,arg2:string):Promise<any>;

export function ClearHistory():Promise<void>;

export function ConfigExists():Promise<boolean>;

export function ConnectSSE(arg1:mcp.HTTPConfig):Promise<mcp.ConnectionStatus>;

export function ConnectStdio(arg1:mcp.StdioConfig):Promise<mcp.ConnectionStatus>;

export function ConnectStreamable(arg1:mcp.HTTPConfig):Promise<mcp.ConnectionStatus>;

export function Disconnect():Promise<void>;

export function GetConfig():Promise<config.AppConfig>;

export function GetHistory():Promise<Array<mcp.HistoryEntry>>;

export function GetPrompt(arg1:string,arg2:string):Promise<any>;

export function GetStatus():Promise<mcp.ConnectionStatus>;

export function ListPrompts():Promise<any>;

export function ListResourceTemplates():Promise<any>;

export function ListResources():Promise<any>;

export function ListTools():Promise<any>;

export function Ping():Promise<string>;

export function ReadResource(arg1:string):Promise<any>;

export function SavePresets(arg1:Array<config.Preset>):Promise<config.AppConfig>;

export function SetLocale(arg1:string):Promise<config.AppConfig>;

export function SetTheme(arg1:string):Promise<config.AppConfig>;
